language: python
python:
  - "2.7"
  - "2.6"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  global:
  matrix:
    - PRINT_FUTURE="0"
    - PRINT_FUTURE="1"

install:
  - python setup.py install
script: "nosetests"
