language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  global:
    - PRINT_FUTURE="0"
  matrix:
    - FLAKE8_VERSION="3.0.0"
    - FLAKE8_VERSION="3.2.1"

matrix:
  include:
    - python: "2.7"
      env: FLAKE8_VERSION="3.0.0" PRINT_FUTURE="1"
    - python: "2.7"
      env: FLAKE8_VERSION="3.2.1" PRINT_FUTURE="1"

install:
  - if [[ -n "$FLAKE8_VERSION" ]]; then pip install flake8=="$FLAKE8_VERSION"; fi
  - grep -v flake8= ./requirements.txt | xargs pip install
  - python setup.py install

script: "nosetests"
